#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
echo "Location of [$(basename "${BASH_SOURCE[0]}")] is: $SCRIPT_DIR"

if [[ "$(uname -a)" == *"Darwin"* ]]; then
    brew update && brew upgrade
    brew install zsh
    brew install vim
    brew install neovim
    brew install fzf
    brew install tmux
    brew install bat
    brew install lua
    brew install exa
else
    echo 0 | sudo -S apt update -y && echo 0 | sudo -S apt upgrade -y && echo 0 | sudo -S apt autoremove -y
    echo 0 | sudo -S apt install zsh vim neovim fzf tmux bat lua5.4 exa -y
fi

#mkdir -p ~/.config/catppuccin
#cd ~/.config/catppuccin

if [[ ! -d ~/.config/catppuccin/nerd-fonts ]]; then
    git clone --depth 1 https://github.com/ryanoasis/nerd-fonts.git
    cd nerd-fonts/
    ./install.sh
fi

if [[ "$(which starship)" == *"not"*"found"* ]]; then
    curl -sS https://starship.rs/install.sh | sh    
fi

if [[ ! -d ~/.oh-my-zsh ]]; then
    sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

if [[ "$(which z)" == *"not"*"found"* ]]; then
    curl -sSfL https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | sh
fi

cd $SCRIPT_DIR

cp -rf aliases.zsh2 ~/
cp -rf .bash_aliases2 ~/
cp -rf .config ~/
cp -rf .tmux.conf ~/
cp -rf .vimrc ~/
cp -rf .warp ~/
cp -rf .zprofile2 ~/
cp -rf .zshrc2 ~/
mkdir -p ${XDG_DATA_HOME:-$HOME/.local/share}/warp-terminal/themes/
cp -rf .warp/themes/* ${XDG_DATA_HOME:-$HOME/.local/share}/warp-terminal/themes/

if [[ -z "$(grep -i '. ~/.zprofile2 > /dev/null 2>&1' ~/.zshrc)" ]]; then
    echo "" >> ~/.zshrc
    echo ". ~/.zprofile2 > /dev/null 2>&1" >> ~/.zshrc
    echo "" >> ~/.zshrc
    echo "Sourcing entry on ~/.zprofile2 has been added to ~/.zshrc"
else
    echo "Sourcing entry on ~/.zprofile2 has already been added, skipping further writes..."
fi

batcat cache --build

#source ~/.zprofile > /dev/null 2>&1
#source ~/.zshrc
