services:
  database:
    container_name: oracle-xe-database
    image: container-registry.oracle.com/database/express:21.3.0-xe
    environment:
      ORACLE_PWD: "123456789"
    volumes:
      - oradata:/opt/oracle/oradata
    ports:
      - "1521:1521"
      - "5500:5500"

volumes:
  oradata:
