services:
  database:
    container_name: oracle-xe-database
    image: container-registry.oracle.com/database/express:21.3.0-xe
    environment:
      ORACLE_PWD: "123456789"
    volumes:
      - oradata:/opt/oracle/oradata
      - ./db-sample-schemas-21.1:/home/oracle/db-sample-schemas:rw
      - ./startup:/opt/oracle/scripts/startup:rw
    ports:
      - "1521:1521"
      - "5500:5500"
    restart: "always"

volumes:
  oradata:
